exp_name: 'w1'
exp_group: 'vq2d'
output_dir: './window/'
log_dir: './log'
workers: 16
print_freq: 100
vis_freq: 1000
eval_vis_freq: 100
seed: 42

# dataset config
dataset:
  name: 'ego4d_vq2d'  # 'ego4d_egotracks'
  name_val: 'ego4d_vq2d'  # 'ego4d_egotracks'
  query_size: 448
  clip_size_fine: 448
  clip_size_coarse: 448
  clip_num_frames: 30 #30
  clip_num_frames_val: 30 #30
  clip_sampling: 'rand'
  clip_reader: 'decord_balance'  # 'decord_random'
  clip_reader_val: 'decord_balance'
  frame_interval: 5
  query_square: True
  query_padding: False
  padding_value: 'mean'  # 'zero' # ['mean', 'zero']

# model config
model:
  backbone_name: 'dinov2'
  backbone_type: 'vitb14'
  bakcbone_use_mae_weight: False
  fix_backbone: True
  num_transformer: 3 # 3
  type_transformer: 'global'
  resolution_transformer: 8
  resolution_anchor_feat: 16
  pe_transformer: 'zero'
  window_transformer: 1
  positive_threshold: 0.3  # 0.2
  positive_topk: 5

# loss config
loss:
  weight_bbox_center: 1.0
  weight_bbox_hw: 1.0
  weight_bbox_giou: 0.3
  weight_bbox_ratio: 1.0
  weight_prob: 10.0  # 100.0
  prob_bce_weight: [0.1, 0.9]  # [1.0, 1.0]

# training config
train:
  resume: False
  batch_size: 2
  total_iteration: 600000
  lr: 0.0001
  weight_decay: 0.005
  schedualr_milestones: [7000, 14000, 20000, 25000]
  schedular_gamma: 0.3
  grad_max: 20.0
  accumulation_step: 1
  aug_clip: True
  aug_query: False
  aug_clip_iter: -1
  aug_brightness: 0.3
  aug_contrast: 0.3
  aug_saturation: 0.2
  aug_crop_scale: 0.8
  aug_crop_ratio_min: 0.8
  aug_crop_ratio_max: 1.2
  aug_affine_degree: 90
  aug_affine_translate: 0.2
  aug_affine_scale_min: 0.8
  aug_affine_scale_max: 1.2
  aug_affine_shear_min: -15.0
  aug_affine_shear_max: 15.0
  aug_prob_color: 1.0
  aug_prob_flip: 0.5
  aug_prob_crop: 1.0
  aug_prob_affine: 1.0
  use_hnm: True

# test config
test:
  batch_size: 2
  compute_metric: True